# netlify.toml

[build]
  # Directory that contains the built site files
  publish = "dist"
  # Build command
  command = "npm run build"
  
[build.environment]
  # Specify Node.js version
  NODE_VERSION = "20"
  # Enable pnpm (since your package-lock suggests you're using pnpm)
  NPM_FLAGS = "--version"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
  # Handle SPA routing - redirect all paths to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; connect-src 'self' https:;"

[functions]
  # Specifies functions directory if you're using Netlify Functions
  directory = "netlify/functions"
  # Set functions timeout
  node_bundler = "esbuild"

[dev]
  # Local dev command
  command = "npm run dev"
  # Set port for local development
  port = 5173
  # Set target port for proxy
  targetPort = 5173
  # Enable debug mode
  publish = "dist"